---
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: test-cluster
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/12"]
        pods:
            cidrBlocks: ["10.244.0.0/16"]
        serviceDomain: cluster.local
    providerSpec:
      value:
        apiVersion: proxmoxproviderconfig.k8s.io/v1alpha1
        kind: ProxmoxClusterProviderSpec
---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  name: mdcp
spec:
  replicas: 1
  selector:
    matchLabels:
      set: controlplane
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: test-cluster
        set: controlplane
    spec:
      versions:
        kubelet: v1.14.1
        controlPlane: v1.14.1
      providerSpec:
        value:
          apiVersion: proxmoxproviderconfig.k8s.io/v1alpha1
          kind: ProxmoxMachineProviderSpec
---
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineDeployment
metadata:
  name: mdw
spec:
  replicas: 3
  selector:
    matchLabels:
      set: node
  template:
    metadata:
      labels:
        cluster.k8s.io/cluster-name: test-cluster
        set: node
    spec:
      versions:
        kubelet: v1.14.1
      providerSpec:
        value:
          apiVersion: proxmoxproviderconfig.k8s.io/v1alpha1
          kind: ProxmoxMachineProviderSpec
